#!/bin/bash
# downloads a local copy of qemu on docker-hub build machines
# curl -L https://github.com/balena-io/qemu/releases/download/v3.0.0%2Bresin/qemu-3.0.0+resin-arm.tar.gz | tar zxvf - -C . && mv qemu-3.0.0+resin-arm/qemu-arm-static .
git clone git://git.qemu.org/qemu.git  
cd qemu  
./configure --target-list=arm-linux-user --static
make  