name: ci

on:
  pull_request:
    branches: [ master, development ]

jobs:
  build_hummingbot:
    name: build + stable tests
    runs-on: "ubuntu-latest"

    steps:
      - uses: actions/checkout@v2
      - name: Cache conda
        uses: actions/cache@v1
        env:
          # Increase this value to reset cache if setup/environment-linux.yml has not changed
          CACHE_NUMBER: 0
        with:
          path: ~/conda_pkgs_dir
          key: ${{ runner.os }}-conda-${{ env.CACHE_NUMBER }}-${{ hashFiles('setup/environment-linux.yml') }}
      - name: Cache build
        uses: actions/cache@v1
        env:
          CACHE_NUMBER: 0
        with:
          path: build
          key: ${{ runner.os }}-conda-${{ env.CACHE_NUMBER }}-${{ hashFiles('hummingbot/*', '') }}

      - uses: goanpeca/setup-miniconda@v1
        with:
          activate-environment: hummingbot
          python-version: 3.7
          channel-priority: true
          environment-file: setup/environment-linux.yml
          use-only-tar-bz2: true # IMPORTANT: This needs to be set for caching to work properly!

      - name: Compile Hummingbot
        shell: bash
        run: |
          source /usr/share/miniconda/etc/profile.d/conda.sh
          conda activate hummingbot
          ./compile
      - name: Run stable tests
        shell: bash
        run: |
          source /usr/share/miniconda/etc/profile.d/conda.sh
          conda activate hummingbot
          nosetests -d -v test/test*.py