name: ci

on:
  pull_request:
    branches: [ master, development ]

jobs:
  build_hummingbot:
    name: build + stable tests
    runs-on: "ubuntu-latest"

    steps:
      # - uses: actions/checkout@v2
      # - uses: actions/setup-python@v2
      #   with:
      #     python-version: 3.x

      - uses: actions/checkout@v2
      - name: Cache conda
        uses: actions/cache@v1
        env:
          # Increase this value to reset cache if etc/example-environment.yml has not changed
          CACHE_NUMBER: 0
        with:
          path: ~/conda_pkgs_dir
          key: ${{ runner.os }}-conda-${{ env.CACHE_NUMBER }}-${{ hashFiles('setup/environment-linux.yml') }}
      - uses: goanpeca/setup-miniconda@v1
        with:
          activate-environment: hummingbot
          python-version: 3.7
          channel-priority: strict
          environment-file: setup/environment-linux.yml
          use-only-tar-bz2: true # IMPORTANT: This needs to be set for caching to work properly!

      # - name: Install Miniconda and nose
      #   shell: bash
      #   run: |
      #     MINICONDA_FILENAME=Miniconda3-latest-Linux-x86_64.sh
      #     curl -o $MINICONDA_FILENAME "https://repo.continuum.io/miniconda/$MINICONDA_FILENAME"
      #     bash ${MINICONDA_FILENAME} -b -f -p $HOME/miniconda3
      #     source /usr/share/miniconda/etc/profile.d/conda.sh
      #     conda install -c anaconda nose

      # - name: Get conda cache dir
      #   id: conda-cache
      #   run: |
      #     source /usr/share/miniconda/etc/profile.d/conda.sh
      #     echo "::set-output name=dir::$(pip cache dir)"
      
      # - name: pip cache
      #   uses: actions/cache@v1
      #   with:
      #     path: ${{ steps.pip-cache.outputs.dir }}
      #     key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
      #     restore-keys: |
      #       ${{ runner.os }}-pip-     

      # - name: Install Hummingbot
      #   shell: bash -l {0}
      #   run: |
      #     echo "source /usr/share/miniconda/etc/profile.d/conda.sh"
      #     ./install
      - name: Compile Hummingbot
        shell: bash
        run: |
          echo "source /usr/share/miniconda/etc/profile.d/conda.sh"
          conda activate hummingbot
          ./compile
      - name: Run stable tests
        shell: bash
        run: |
          echo "source /usr/share/miniconda/etc/profile.d/conda.sh"
          conda activate hummingbot
          nosetests -d -v test/test*.py