name: ci

on:
  pull_request:
    branches: [ master, development ]

jobs:
  build_hummingbot:
    name: build + stable tests
    runs-on: "ubuntu-latest"

    steps:
      - uses: actions/checkout@v2
    
      # Use cache's hashFiles function to check for changes in core code
      - name: Check for core changes
        id: program-changes
        uses: actions/cache@v2
        env:
          CACHE_NUMBER: 0
        with:
          path: hummingbot
          key: ${{ runner.os }}-build-${{ env.CACHE_NUMBER }}-${{ hashFiles('setup/*', 'hummingbot/*', 'build/*', '**/*.py', '**/*.py*', '**/*.pxd') }}

      - name: Cache conda dependencies
        id: conda-dependencies
        uses: actions/cache@v2
        env:
          # Increase this value to reset cache if setup/environment-linux.yml has not changed
          CONDA_CACHE_NUMBER: 0
        with:
          path: |
            /home/runner/conda_pkgs_dir/
            /usr/share/miniconda/envs/hummingbot
          key: ${{ runner.os }}-conda-${{ env.CONDA_CACHE_NUMBER }}-${{ hashFiles('setup/environment-linux.yml') }}

      # Only run remaining steps if there is a change to the core code
      # Restore cached conda dependencies if setup/environment-linux.yml is unchanged
      - uses: goanpeca/setup-miniconda@v1
        if: steps.program-changes.outputs.cache-hit != 'true' && steps.conda-dependencies.outputs.cache-hit != 'true'
        with:
          activate-environment: hummingbot
          python-version: 3.7
          channel-priority: true
          environment-file: setup/environment-linux.yml
          use-only-tar-bz2: true # IMPORTANT: This needs to be set for caching to work properly!
  
      - name: Compile Hummingbot
        shell: bash
        if: steps.program-changes.outputs.cache-hit != 'true'
        run: |
          source /usr/share/miniconda/etc/profile.d/conda.sh
          conda activate hummingbot
          ./compile
      - name: Run stable tests
        if: steps.program-changes.outputs.cache-hit != 'true'
        shell: bash
        run: |
          source /usr/share/miniconda/etc/profile.d/conda.sh
          conda activate hummingbot
          nosetests -d -v test/test*.py